AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test lambda with sam
Resources:
    Samfunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python3.9
            CodeUri: 's3://project-gits/fcff61a71ee121c3fae9894faff67824'
            Description: sample sam for lambda function
            Events:
             SamSech:
              Type: Schedule
              Properties:
               Schedule: rate(10 minutes)

              
            